In [5]:
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from ydata_profiling import ProfileReport
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE

In [7]:
df = pd.read_csv("C:/Users/USER/Downloads/WineQT.csv")

In [8]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [9]:
df.tail(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1133,6.7,0.320,0.44,2.4,0.061,24.0,34.0,0.99484,3.29,0.80,11.6,7,1584
1134,7.5,0.310,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4,6,1586
1135,5.8,0.610,0.11,1.8,0.066,18.0,28.0,0.99483,3.55,0.66,10.9,6,1587
1136,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.740,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [10]:
df.shape

(1143, 13)

In [11]:
df.nunique()

fixed acidity             91
volatile acidity         135
citric acid               77
residual sugar            80
chlorides                131
free sulfur dioxide       53
total sulfur dioxide     138
density                  388
pH                        87
sulphates                 89
alcohol                   61
quality                    6
Id                      1143
dtype: int64

In [12]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [13]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

In [13]:
profile = ProfileReport(df, title="Profiling Report")
profile.to_file(r"C:\Users\USER\Documents\python\your_report.html")

Summarize dataset: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 191/191 [00:24<00:00,  7.65it/s, Completed]
Generate report structure: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:04<00:00,  4.46s/it]
Render HTML: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:04<00:00,  4.68s/it]
Export report to file: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00, 44.45it/s]

there is no duplicate rows or missing values in this dataset

## preprocessing

In [15]:
df.duplicated().sum()

0

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality, Id]
Index: []

## dropping duplicates

In [17]:
df_1 = df.drop_duplicates()
df_1
#there are no duplicate rows
#df_1 is after dropping duplicates

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

## outliers

In [18]:
df_1.mean()

fixed acidity             8.311111
volatile acidity          0.531339
citric acid               0.268364
residual sugar            2.532152
chlorides                 0.086933
free sulfur dioxide      15.615486
total sulfur dioxide     45.914698
density                   0.996730
pH                        3.311015
sulphates                 0.657708
alcohol                  10.442111
quality                   5.657043
Id                      804.969379
dtype: float64

In [19]:
upper_limit = df_1.mean() + 3 * df_1.std()
upper_limit

fixed acidity             13.553896
volatile acidity           1.070238
citric acid                0.858422
residual sugar             6.599905
chlorides                  0.228735
free sulfur dioxide       46.366944
total sulfur dioxide     144.261089
density                    1.002506
pH                         3.781007
sulphates                  1.168904
alcohol                   13.688698
quality                    8.074516
Id                      2196.960728
dtype: float64

In [20]:
lower_limit = df_1.mean() - 3 * df_1.std()
lower_limit

fixed acidity             3.068326
volatile acidity         -0.007561
citric acid              -0.321694
residual sugar           -1.535600
chlorides                -0.054869
free sulfur dioxide     -15.135973
total sulfur dioxide    -52.431693
density                   0.990955
pH                        2.841023
sulphates                 0.146512
alcohol                   7.195525
quality                   3.239570
Id                     -587.021970
dtype: float64

In [21]:
df_1.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [22]:
temp = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol']

In [29]:
for i in temp:
    lower_limit = df_1[i].mean() - 3 * df_1[i].std()
    upper_limit = df_1[i].mean() + 3 * df_1[i].std()
    df_1 = df_1[(df_1[i] < upper_limit) & (df_1[i] > lower_limit)]
df_1

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [39]:

df_2 = df_1[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality']]
df_2

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5

## missing values

In [24]:
#there is no missing value

## standardization

In [40]:
scaled = MinMaxScaler().fit_transform(df_2)
df_scaled = pd.DataFrame(scaled, columns = list(df_2.columns))

In [41]:
df_scaled

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.292683,0.630435,0.000000,0.194444,0.387755,0.250,0.241379,0.658849,0.719512,0.348485,0.148936,0.4
1,0.341463,0.826087,0.000000,0.388889,0.612245,0.600,0.525862,0.552239,0.341463,0.530303,0.234043,0.4
2,0.341463,0.695652,0.052632,0.305556,0.551020,0.350,0.413793,0.573561,0.414634,0.484848,0.234043,0.4
3,0.756098,0.173913,0.736842,0.194444,0.377551,0.400,0.465517,0.680171,0.292683,0.378788,0.234043,0.6
4,0.292683,0.630435,0.000000,0.194444,0.387755,0.250,0.241379,0.658849,0.719512,0.348485,0.148936,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...
930,0.158537,0.423913,0.171053,0.305556,0.387755,0.700,0.293103,0.439232,0.609756,0.636364,0.489362,0.6
931,0.219512,0.543478,0.105263,0.194444,0.306122,0.675,0.275862,0.521322,0.609756,0.742424,0.170213,0.6
932,0.146341,0.521739,0.105263,0.222222,0.530612,0.775,0.327586,0.349680,0.646341,0.378788,0.382979,0.4
933,0.109756,0.467391,0.131579,0.277778,0.244898,0.950,0.387931,0.373134,0.731707,0.651515,0.531915,0.6
934,0.109756,0.570652,0.157895,0.222222,0.377551,0.775,0.327586,0.410448,0.792683,0.575758,0.319149,0.4

## data imbalancing

In [42]:
Y = df_scaled['quality']
X = df_scaled.drop('quality', axis = 1)

In [43]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)

In [44]:
X_train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
386,0.243902,0.565217,0.026316,0.250000,0.295918,0.200,0.146552,0.573561,0.670732,0.515152,0.148936
624,0.439024,0.434783,0.500000,0.083333,0.591837,0.100,0.103448,0.537313,0.341463,0.287879,0.148936
892,0.268293,0.445652,0.171053,0.222222,0.204082,0.425,0.137931,0.438166,0.353659,0.530303,0.255319
85,0.219512,0.521739,0.236842,0.194444,0.418367,0.425,0.689655,0.552239,0.817073,0.363636,0.127660
812,0.121951,0.423913,0.000000,0.250000,0.265306,0.975,0.413793,0.360341,0.756098,0.909091,0.425532
...,...,...,...,...,...,...,...,...,...,...,...
835,0.219512,0.597826,0.000000,0.194444,0.428571,0.525,0.284483,0.574627,0.585366,0.621212,0.212766
192,0.719512,0.293478,0.618421,0.166667,0.816327,0.125,0.068966,0.701493,0.463415,0.636364,0.234043
629,0.158537,0.489130,0.368421,0.250000,0.102041,0.300,0.370690,0.226013,0.597561,0.409091,0.872340
559,0.475610,0.782609,0.447368,0.055556,0.122449,0.075,0.034483,0.417910,0.243902,0.227273,0.085106
684,0.329268,0.152174,0.342105,0.222222,0.142857,0.450,0.612069,0.371002,0.280488,0.696970,0.468085

## filter

In [51]:
X = pd.DataFrame(X_train)
Y = pd.DataFrame(Y_train, columns = ['quality'])
df_train_final = pd.concat([X,Y], axis = 'columns')

In [52]:
df_train_final

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
386,0.243902,0.565217,0.026316,0.250000,0.295918,0.200,0.146552,0.573561,0.670732,0.515152,0.148936,0.6
624,0.439024,0.434783,0.500000,0.083333,0.591837,0.100,0.103448,0.537313,0.341463,0.287879,0.148936,0.4
892,0.268293,0.445652,0.171053,0.222222,0.204082,0.425,0.137931,0.438166,0.353659,0.530303,0.255319,0.6
85,0.219512,0.521739,0.236842,0.194444,0.418367,0.425,0.689655,0.552239,0.817073,0.363636,0.127660,0.6
812,0.121951,0.423913,0.000000,0.250000,0.265306,0.975,0.413793,0.360341,0.756098,0.909091,0.425532,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...
835,0.219512,0.597826,0.000000,0.194444,0.428571,0.525,0.284483,0.574627,0.585366,0.621212,0.212766,0.4
192,0.719512,0.293478,0.618421,0.166667,0.816327,0.125,0.068966,0.701493,0.463415,0.636364,0.234043,0.6
629,0.158537,0.489130,0.368421,0.250000,0.102041,0.300,0.370690,0.226013,0.597561,0.409091,0.872340,0.4
559,0.475610,0.782609,0.447368,0.055556,0.122449,0.075,0.034483,0.417910,0.243902,0.227273,0.085106,0.6
684,0.329268,0.152174,0.342105,0.222222,0.142857,0.450,0.612069,0.371002,0.280488,0.696970,0.468085,0.6

In [53]:
df_train_final.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
fixed acidity,1.000000,-0.269897,0.685069,0.211842,0.243551,-0.156559,-0.096627,0.649689,-0.707817,0.172918,-0.068278,0.112313
volatile acidity,-0.269897,1.000000,-0.587065,0.051459,0.063401,0.015473,0.137993,0.004400,0.222803,-0.320816,-0.169817,-0.341118
citric acid,0.685069,-0.587065,1.000000,0.179095,0.133207,-0.086228,-0.025728,0.340458,-0.504513,0.268727,0.133199,0.246986
residual sugar,0.211842,0.051459,0.179095,1.000000,0.213414,0.004047,0.093164,0.342041,-0.049723,0.022615,0.148063,0.003181
chlorides,0.243551,0.063401,0.133207,0.213414,1.000000,0.024296,0.155377,0.393635,-0.182442,-0.026794,-0.236647,-0.161419
free sulfur dioxide,-0.156559,0.015473,-0.086228,0.004047,0.024296,1.000000,0.639670,-0.036065,0.099342,0.062155,-0.054531,-0.047861
total sulfur dioxide,-0.096627,0.137993,-0.025728,0.093164,0.155377,0.639670,1.000000,0.139288,0.000529,-0.066555,-0.265394,-0.210366
density,0.649689,0.004400,0.340458,0.342041,0.393635,-0.036065,0.139288,1.000000,-0.287536,0.105839,-0.526283,-0.213641
pH,-0.707817,0.222803,-0.504513,-0.049723,-0.182442,0.099342,0.000529,-0.287536,1.000000,0.026659,0.169878,-0.078411
sulphates,0.172918,-0.320816,0.268727,0.022615,-0.026794,0.062155,-0.066555,0.105839,0.026659,1.000000,0.219633,0.409110
alcohol,-0.068278,-0.169817,0.133199,0.148063,-0.236647,-0.054531,-0.265394,-0.526283,0.169878,0.219633,1.000000,0.495165
quality,0.112313,-0.341118,0.246986,0.003181,-0.161419,-0.047861,-0.210366,-0.213641,-0.078411,0.409110,0.495165,1.000000

In [58]:
abs(df_train_final.corr()['quality'].sort_values(ascending = False)) >= 0.25

quality                  True
alcohol                  True
sulphates                True
citric acid             False
fixed acidity           False
residual sugar          False
free sulfur dioxide     False
pH                      False
chlorides               False
total sulfur dioxide    False
density                 False
volatile acidity         True
Name: quality, dtype: bool